Calculus/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^(?P<company_id>\d+)/(?P<year_id>\d+)/(?P<version_id>\d+)/bilanz/', include('balancesheet.urls', namespace='balancesheet')),
    url(r'^api/bilanz/', include('balancesheet.urls_api', namespace='balancesheet_api')),
    url(r'^', include('core.urls', namespace='core'))
]

balancesheet/urls.py
from django.conf.urls import url
from .views import balancesheet, difference

urlpatterns = [
    url(r'^$', balancesheet.BalanceSheetView.as_view(), name='balancesheet'),
]

core/urls.py
from django.conf.urls import url
from .views import company, year, version

urlpatterns = [
    # Companies
    url(r'^$', company.CompanyView.as_view(), name='company_index'),

    # Years
    url(r'^(?P<company_id>\d+)/$', year.YearListView.as_view(), name='year_index'),
    url(r'^(?P<company_id>\d+)/(?P<year_id>\d+)/detail$', year.YearDetailView.as_view(), name='year_detail'),
    
    #Versionen     
    url(r'^(?P<company_id>\d+)/(?P<year_id>\d+)/$', version.VersionListView.as_view(), name='version_index'),
]

core/models.py
from django.db import models

# Create your models here.


class Company(models.Model):
    name = models.CharField(max_length=100, blank=True, null=True, verbose_name='Name')
    shortname = models.CharField(max_length=5, unique=True, verbose_name='Kürzel')
    type = models.CharField(max_length=50, verbose_name='Gesellschaftstyp')

    class Meta:
        verbose_name = 'Gesellschaft'
        verbose_name_plural = 'Gesellschaften'

    def __str__(self):
        return self.name


class Year(models.Model):
    start_date = models.DateField(verbose_name='Startdatum')
    end_date = models.DateField(verbose_name='Enddatum')
    prior_year = models.ForeignKey('self', blank=True, null=True, verbose_name='Vorjahr')
    company = models.ForeignKey('Company', verbose_name='Gesellschaft', on_delete=models.PROTECT)

    class Meta:
        ordering = ['end_date']
        unique_together = ('company', 'end_date')
        verbose_name = 'Wirtschaftsjahr'
        verbose_name_plural = 'Wirtschaftsjahre'

    def __str__(self):
        return self.end_date.strftime("%d.%m.%Y")


class Version(models.Model):
    year = models.ForeignKey('Year', verbose_name='Jahr', on_delete=models.PROTECT)
    name = models.CharField(max_length=100, verbose_name='Bezeichnung')
    shortname = models.CharField(max_length=5, verbose_name='Kürzel')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')
    closed = models.BooleanField(default=False, verbose_name='Geschlossen')
    py_version = models.ForeignKey(
        'self',
        blank=True,
        null=True,
        related_name='version_py_version',
        verbose_name='Vorjahresversion',
        on_delete=models.PROTECT)  # Was ist die Vergleichsversion im Vorjahr?
    tu_version = models.ForeignKey(
        'self',
        blank=True,
        null=True,
        related_name='version_tu_version',
        verbose_name='Matching-Version',
        on_delete=models.PROTECT)  # Welche Version im Vorjahr hat aktualisierte Werte?

    class Meta:
        unique_together = ('year', 'shortname')
        verbose_name = 'Version'
        verbose_name_plural = 'Versionen'

    def __str__(self):
        return self.name

core/views.py
from django.shortcuts import render

# Create your views here.

core/views/company.py
from django.shortcuts import render, get_list_or_404
from django.views import View

from core.models import Company 


class CompanyView(View):
    template_name = 'core/company_view.html'

    def get(self, request, *args, **kwargs):

        c = Company.objects.all()
        context = {
            'Companies': c,
            
        }
        return render(request, self.template_name, context)

core/views/index.py
from django.shortcuts import render, get_list_or_404
from django.views import View

from core.models import Company 


class CompanyView(View):
    template_name = 'core/company_view.html'

    def get(self, request, *args, **kwargs):

        c = get_list_or_404(Company)
        context = {
            'Companies': c,
            
        }
        return render(request, self.template_name, context)

core/views/version.py
__author__ = 'CF'
# -*- coding: utf-8 -*-

from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.views import View
from django.http import HttpResponseForbidden, HttpResponse

from core.models import Company, Year, Version
import pdb

class VersionListView(View):
    template_name = 'core/version_list.html'

    def get(self, request, *args, **kwargs):

        v = Version.objects.filter(year_id=kwargs['year_id'])

        # Feststellen, ob Jahr gelöscht werden kann
        for elem in v:
            if elem.version_py_version.count() > 0 or elem.version_tu_version.count() > 0:
                elem.deletable = False
            else:
                elem.deletable = True

        context = {
            'Company_id': kwargs['company_id'],
            'Year_id': kwargs['year_id'],
            'Versions': v
        }
            
        return render(request, self.template_name, context)
        
        
#     def post(self, request, *args, **kwargs):
#         sd = dateutil.parser.parse(request.POST.get('inputFromDate')).date()
#         ed = dateutil.parser.parse(request.POST.get('inputToDate')).date()
#         pyid = request.POST.get('prior_year_id')
#         ny = Year(start_date=sd, end_date=ed, prior_year_id=pyid, company_id=kwargs['company_id'])
#         if sd <= ed:
#             ny.save()
#             messages.success(request, 'Neues Jahr hinzugefügt')
#         else:
#             messages.error(request, 'Das "Bis"-Datum muss zeitlich nach dem "Von"-Datum liegen.')
#
#         y = Year.objects.filter(company_id=kwargs['company_id'])
#         n = y.last().end_date + datetime.timedelta(days=1)
#
#         if calendar.isleap(y.last().end_date.year+1):
#             ye = y.last().end_date + datetime.timedelta(days=366)
#         else:
#             ye = y.last().end_date + datetime.timedelta(days=365)
#
#         # Feststellen, ob Jahr gelöscht werden kann
#         for elem in y:
#             if elem.year_set.count() > 0 or elem.version_set.count() > 0:
#                 elem.deletable = False
#             else:
#                 elem.deletable = True
#
#         context = {
#             'Company_id': kwargs['company_id'],
#             'Years':y,
#             'Yearend':ye,
#             'Nextyear':n
#             }
#
#         return render(request, self.template_name, context)
#
#
# class YearDetailView(View):
#
#     def delete(self, request, *args, **kwargs):
#         y = get_object_or_404(Year, id=kwargs['year_id'])
#         if y.year_set.count() > 0 or y.version_set.count() > 0:
#             return HttpResponseForbidden
#         else:
#             y.delete()
#             return HttpResponse(status=200)

core/views/year.py
__author__ = 'CF'
# -*- coding: utf-8 -*-

from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.views import View
from django.http import HttpResponseForbidden, HttpResponse

import datetime, dateutil.parser, calendar, pdb

from core.models import Company, Year


class YearListView(View):
    template_name = 'core/year_list.html'

    def get(self, request, *args, **kwargs):

        y = Year.objects.filter(company_id=kwargs['company_id'])
        n = y.last().end_date + datetime.timedelta(days=1)
    
        if calendar.isleap(y.last().end_date.year+1):
            ye = y.last().end_date + datetime.timedelta(days=366)
        else:
            ye = y.last().end_date + datetime.timedelta(days=365)
    
        # Feststellen, ob Jahr gelöscht werden kann
        for elem in y:
            if elem.year_set.count() > 0 or elem.version_set.count() > 0:
                elem.deletable = False
            else:
                elem.deletable = True
            #pdb.set_trace()


        context = {
            'Company_id': kwargs['company_id'],
            'Years':y,
            'Yearend':ye,
            'Nextyear':n            }
            
        return render(request, self.template_name, context)
        
        
    def post(self, request, *args, **kwargs):
        sd = dateutil.parser.parse(request.POST.get('inputFromDate')).date()
        ed = dateutil.parser.parse(request.POST.get('inputToDate')).date()
        pyid = request.POST.get('prior_year_id')
        ny = Year(start_date=sd, end_date=ed, prior_year_id=pyid, company_id=kwargs['company_id'])
        if sd <= ed:
            ny.save()
            messages.success(request, 'Neues Jahr hinzugefügt')
        else:
            messages.error(request, 'Das "Bis"-Datum muss zeitlich nach dem "Von"-Datum liegen.')
        
        y = Year.objects.filter(company_id=kwargs['company_id'])
        n = y.last().end_date + datetime.timedelta(days=1)
    
        if calendar.isleap(y.last().end_date.year+1):
            ye = y.last().end_date + datetime.timedelta(days=366)
        else:
            ye = y.last().end_date + datetime.timedelta(days=365)
    
        # Feststellen, ob Jahr gelöscht werden kann
        for elem in y:
            if elem.year_set.count() > 0 or elem.version_set.count() > 0:
                elem.deletable = False
            else:
                elem.deletable = True
    
        context = {
            'Company_id': kwargs['company_id'],
            'Years':y,
            'Yearend':ye,
            'Nextyear':n
            }
    
        return render(request, self.template_name, context)


class YearDetailView(View):

    def delete(self, request, *args, **kwargs):
        y = get_object_or_404(Year, id=kwargs['year_id'])
        if y.year_set.count() > 0 or y.version_set.count() > 0:
            return HttpResponseForbidden
        else:
            y.delete()
            return HttpResponse(status=200)

core/templates/core/company_view.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}Gesellschaften{% endblock %}
{% block content %}
<div class="container">
    <h1>Gesellschaft auswählen</h1>
    {% if Companies %}
    <table class="table table-hover table-bordered table-responsive">
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
            </tr>
        </thead>
        <tbody>
            {% for c in Companies %}
            <tr>
                <td><a href="{% url 'core:year_index' company_id=c.id %}">{{ c.shortname }}</a></td>
                <td><a href="{% url 'core:year_index' company_id=c.id %}">{{ c.name }}</a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
    <h3 class="alert-danger">Keine Gesellschaften vorhanden!</h3>
    {% endif %}
</div>
{% endblock %}

core/templates/core/version_list.html
{% extends "base.html" %}

{% block title %}Version auswählen{% endblock %}

{% block content %}
    <div class="container">
        <h1>Version auswählen</h1>

        {% if messages %}
            <ul class="messages list-unstyled">
                {% for message in messages %}
                    <li{% if message.tags %} class="alert alert-{{ message.tags }} text-center"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}

        <div class="text-right">
            <a href="javascript:void(0);"><span id="new_version_button" class="glyphicon glyphicon-plus-sign btn btn-default" title="Neue Version anlegen"  data-toggle="modal" data-target="#modalNewVersion"></span></a>
        </div>

        {% if Versions %}
            <div>
                <table class="table table-hover table-bordered table-responsive">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>Beschreibung</th>
                        <th>Erstellt am</th>
                        <th>Status</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for v in Versions %}
                        <tr>
                            <td><a href="{% url 'balancesheet:balancesheet' company_id=Company_id year_id=Year_id version_id=v.id %}">{{ v.shortname }}</a></td>
                            <td><a href="{% url 'balancesheet:balancesheet' company_id=Company_id year_id=Year_id version_id=v.id %}">{{ v.name }}</a></td>
                            <td><a href="{% url 'balancesheet:balancesheet' company_id=Company_id year_id=Year_id version_id=v.id %}">{{ v.created_at | date:"d.m.Y" }}</a></td>
                            <td>{% if v.deletable %}<button class="btn btn-danger btn-xs delete-button" data-delete-version={{ v.id }}><span class="glyphicon glyphicon-remove-sign" title="Version löschen"></span></button></form>{% endif %}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        {% else %}
            <div>
                <h3 class="alert-danger">Keine Versionen vorhanden!</h3>
            </div>
        {% endif %}


        <!-- Modal -->
        <div class="modal fade" id="modalNewVersion" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    {% comment %}<form role="form" action="{% url 'core:year_index' company_id=Company_id %}" method="post">
                        {% csrf_token %}
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                            <h4 class="modal-title" id="modelNewYearLabel">Neues Jahr anlegen</h4>
                        </div>
                        <div class="modal-body">
                            <div class="form-group">
                                <label for="inputFromDate">Von</label>
                                <input type="date" class="form-control" name="inputFromDate" id="inputFromDate" readonly="readonly" value="{{ Nextyear | date:'d.m.Y' }}">
                            </div>
                            <div class="form-group">
                                <label for="inputToDate">Bis</label>
                                <input type="date" class="form-control" name="inputToDate" id="inputToDate" value="{{ Yearend | date:'d.m.Y' }}">
                            </div>
                            <div>
                                {% if Years %}
                                    <input type="hidden" value="{{ Years.last.id }}" name="prior_year_id" />
                                {% else %}
                                    <input type="hidden" value="None" name="prior_year_id" />
                                {% endif %}
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="reset" class="btn btn-default" data-dismiss="modal">Schließen</button>
                            <button type="submit" class="btn btn-primary">Speichern</button>
                        </div>
                    </form>{% endcomment %}
                </div>
            </div>
        </div>
    </div>
    
    <script type="text/javascript">
    function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = jQuery.trim(cookies[i]);
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
    var csrftoken = getCookie('csrftoken');
    $('.delete-button').click(function() {
        var version_id = $(this).attr("data-delete-version");
        $.ajax({
            url: {% url 'core:year_index' company_id=Company_id %} + year_id,
            beforeSend: function (xhr) {
                xhr.setRequestHeader('X-CSRFToken', csrftoken);
            },
            type: 'DELETE',
            success: function(result) {
                console.log("Delete successful!");
                window.location = {% url 'core:year_index' company_id=Company_id %};
            }
        });
    });
</script>
{% endblock %}

core/templates/core/year_detail.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}Jahr Details{% endblock %}
{% block content %}
<div class="container">

</div>
{% endblock %}

core/templates/core/year_list.html
{% extends "base.html" %}

{% block title %}Jahr auswählen{% endblock %}

{% block content %}
    <div class="container">
        <h1>Jahr auswählen</h1>

        {% if messages %}
            <ul class="messages list-unstyled">
                {% for message in messages %}
                    <li{% if message.tags %} class="alert alert-{{ message.tags }} text-center"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}

        <div class="text-right">
            <a href="javascript:void(0);"><span id="new_year_button" class="glyphicon glyphicon-plus-sign btn btn-default" title="Neues Jahr anlegen"  data-toggle="modal" data-target="#modalNewYear"></span></a>
        </div>

        {% if Years %}
            <div>
                <table class="table table-hover table-bordered table-responsive">
                    <thead>
                    <tr>
                        <th>Von</th>
                        <th>Bis</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for y in Years %}
                        <tr>
                            <td><a href="{% url 'core:version_index' company_id=Company_id year_id=y.id %}">{{ y.start_date | date:"d.m.Y" }}</a></td>
                            <td><a href="{% url 'core:version_index' company_id=Company_id year_id=y.id %}">{{ y.end_date | date:"d.m.Y" }}</a></td>
                            <td>{% if y.deletable %}<button class="btn btn-danger btn-xs delete-button" data-delete-year={{ y.id }}><span class="glyphicon glyphicon-remove-sign" title="Jahr löschen"></span></button></form>{% endif %}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        {% else %}
            <div>
                <h3 class="alert-danger">Keine Jahre vorhanden!</h3>
            </div>
        {% endif %}


        <!-- Modal -->
        <div class="modal fade" id="modalNewYear" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <form role="form" action="{% url 'core:year_index' company_id=Company_id %}" method="post">
                        {% csrf_token %}
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                            <h4 class="modal-title" id="modelNewYearLabel">Neues Jahr anlegen</h4>
                        </div>
                        <div class="modal-body">
                            <div class="form-group">
                                <label for="inputFromDate">Von</label>
                                <input type="date" class="form-control" name="inputFromDate" id="inputFromDate" readonly="readonly" value="{{ Nextyear | date:'d.m.Y' }}">
                            </div>
                            <div class="form-group">
                                <label for="inputToDate">Bis</label>
                                <input type="date" class="form-control" name="inputToDate" id="inputToDate" value="{{ Yearend | date:'d.m.Y' }}">
                            </div>
                            <div>
                                {% if Years %}
                                    <input type="hidden" value="{{ Years.last.id }}" name="prior_year_id" />
                                {% else %}
                                    <input type="hidden" value="None" name="prior_year_id" />
                                {% endif %}
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="reset" class="btn btn-default" data-dismiss="modal">Schließen</button>
                            <button type="submit" class="btn btn-primary">Speichern</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    
    <script type="text/javascript">
    function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = jQuery.trim(cookies[i]);
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
    var csrftoken = getCookie('csrftoken');
    $('.delete-button').click(function() {
        var year_id = $(this).attr("data-delete-year");
        $.ajax({
            url: {% url 'core:year_index' company_id=Company_id %} + year_id,
            beforeSend: function (xhr) {
                xhr.setRequestHeader('X-CSRFToken', csrftoken);
            },
            type: 'DELETE',
            success: function(result) {
                console.log("Delete successful!");
                window.location = {% url 'core:year_index' company_id=Company_id %};
            }
        });
    });
</script>
{% endblock %}